import { StyleSheet, Platform } from 'react-native';

export const chatStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#212121',
  },
  flex: {
    flex: 1,
  },
  contentArea: {
    flex: 1,
    justifyContent: 'center',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#212121',
  },
  loadingText: {
    color: '#9ca3af',
    marginTop: 12,
    fontSize: 16,
  },
  welcomeContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
    paddingVertical: 60,
    minHeight: 200,
    maxHeight: '50%',
  },
  welcomeTitle: {
    fontSize: 32,
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: 12,
    textAlign: 'center',
  },
  welcomeSubtitle: {
    fontSize: 16,
    color: '#9ca3af',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 8,
  },
  modelInfo: {
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  messagesList: {
    flex: 1,
  },
  messagesContainer: {
    padding: 20,
    paddingBottom: 10,
  },
  userMessageWrapper: {
    flexDirection: 'column',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    marginVertical: 8,
    width: '100%',
  },
  userHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginBottom: 4,
  },
  userHeaderText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6b7280',
    marginRight: 8,
  },
  userAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#2563eb',
  },
  userInitial: {
    fontSize: 12,
    fontWeight: '600',
    color: '#ffffff',
  },
  userBubble: {
    backgroundColor: '#2563eb',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 18,
    maxWidth: '80%',
    justifyContent: 'center',
    minHeight: 38,
    alignSelf: 'flex-end',
    marginLeft: 20,
  },
  userMessageText: {
    fontSize: 16,
    color: '#ffffff',
    fontFamily: Platform.select({
      ios: 'System',
      android: 'Roboto',
    }),
  },
  agentMessageWrapper: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    marginVertical: 8,
    width: '100%',
  },
  agentHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginBottom: 4,
  },
  agentAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#374151',
  },
  agentInitial: {
    fontSize: 12,
    fontWeight: '600',
    color: '#ffffff',
  },
  agentHeaderText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6b7280',
    marginLeft: 8,
  },
  agentBubble: {
    backgroundColor: '#374151',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 18,
    maxWidth: '80%',
    justifyContent: 'center',
    minHeight: 38,
    alignSelf: 'flex-start',
    marginRight: 20,
  },
  agentMessageText: {
    fontSize: 16,
    color: '#ffffff',
    fontFamily: Platform.select({
      ios: 'System',
      android: 'Roboto',
    }),
  },
  inputContainer: {
    paddingHorizontal: 0,
    paddingTop: 25,
    paddingBottom: 15,
    backgroundColor: '#212121',
    marginBottom: Platform.OS === 'android' ? 5 : 0,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#374151',
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginBottom: 0,
    minHeight: 48,
    marginHorizontal: 0,
  },
  textInput: {
    flex: 1,
    color: '#ffffff',
    fontSize: 16,
    lineHeight: 22,
    maxHeight: 120,
    paddingVertical: 0,
    fontFamily: Platform.select({
      ios: 'System',
      android: 'Roboto',
    }),
  },
  sendButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  sendButtonActive: {
    backgroundColor: '#ffffff',
  },
  sendButtonInactive: {
    backgroundColor: 'transparent',
  },
  sendIcon: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#212121',
  },
  inputHint: {
    fontSize: 12,
    color: '#6b7280',
    textAlign: 'center',
  },
  dateSeparator: {
    marginVertical: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dateText: {
    fontSize: 14,
    color: '#6b7280',
    fontWeight: '600',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 4,
    ...Platform.select({
      ios: {
        paddingTop: 14,
      },
      android: {
        paddingTop: 20,
      },
    }),
    paddingVertical: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: '#374151',
    backgroundColor: '#1f2937',
    minHeight: 52,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  backButton: {
    width: 26,
    height: 26,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 13,
    marginLeft: 0,
  },
  backArrow: {
    fontSize: 18,
    color: '#ffffff',
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 26,
    includeFontPadding: false as unknown as boolean,
    textAlignVertical: 'center' as any,
    transform: [{ translateY: Platform.OS === 'android' ? -0.5 : 0 }],
  },
  headerInfo: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginLeft: 0,
    minWidth: 0,
  },
  headerAvatar: {
    width: 22,
    height: 22,
    borderRadius: 11,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 4,
    borderWidth: 0,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  headerInitial: {
    fontSize: 12,
    fontWeight: '700',
    color: '#ffffff',
    fontFamily: Platform.select({
      ios: 'System',
      android: 'Roboto',
    }),
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#f9fafb',
    flex: 1,
    lineHeight: 20,
    includeFontPadding: false as unknown as boolean,
    flexShrink: 1,
    textAlign: 'left',
    textAlignVertical: 'center' as any,
    fontFamily: Platform.select({
      ios: 'System',
      android: 'Roboto',
    }),
  },
  headerSpacer: {
    width: 2,
  },
  modelButton: {
    maxWidth: 110,
    minWidth: 72,
    height: 32,
    paddingHorizontal: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 18,
    backgroundColor: 'rgba(37, 99, 235, 0.15)',
    marginRight: 4,
  },
  modelButtonText: {
    fontSize: 11,
    color: '#f9fafb',
    fontWeight: '600',
  },
  threadsButton: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 0,
    backgroundColor: 'transparent',
  },
  threadsIcon: {
    fontSize: 20,
    color: '#f9fafb',
    fontWeight: '600',
  },
  dropdownBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.2)',
    zIndex: 999,
  },
  modelDropdown: {
    position: 'absolute',
    right: 12,
    backgroundColor: '#111827',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: '#2f343a',
    width: 260,
    maxHeight: 360,
    zIndex: 1000,
  },
  modelDropdownTitle: {
    fontSize: 13,
    color: '#9ca3af',
    fontWeight: '600',
    marginBottom: 8,
    paddingHorizontal: 6,
  },
  modelOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 8,
  },
  modelOptionText: {
    fontSize: 14,
    color: '#f3f4f6',
    flex: 1,
    marginRight: 8,
  },
  modelServiceTag: {
    fontSize: 12,
    color: '#93c5fd',
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    textTransform: 'capitalize',
  },
  emptyModels: {
    paddingVertical: 16,
    alignItems: 'center',
  },
  threadsModal: {
    backgroundColor: '#212121',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    maxHeight: '95%',
    minHeight: '90%',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
      },
      android: {
        elevation: 0,
        borderTopWidth: 1,
        borderTopColor: 'rgba(255, 255, 255, 0.1)',
      },
    }),
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  swipeIndicator: {
    width: 40,
    height: 4,
    backgroundColor: '#6b7280',
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 8,
    marginBottom: 4,
  },
  threadsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#2f343a',
  },
  threadsTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#ffffff',
  },
  closeButton: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeIcon: {
    fontSize: 24,
    color: '#ffffff',
  },
  newThreadButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    backgroundColor: '#2563eb',
    borderRadius: 20,
    marginHorizontal: 60,
    marginVertical: 16,
  },
  newThreadIcon: {
    fontSize: 18,
    color: '#ffffff',
    marginRight: 6,
  },
  newThreadText: {
    fontSize: 14,
    color: '#ffffff',
    fontWeight: '500',
  },
  threadsList: {
    flex: 1,
  },
  threadItemContainer: {
    backgroundColor: '#212121',
  },
  threadsContainer: {
    paddingHorizontal: 16,
  },
  emptyThreads: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptyText: {
    fontSize: 16,
    color: '#9ca3af',
    fontWeight: '500',
    textAlign: 'center',
  },
  emptySubtext: {
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
    marginTop: 8,
    lineHeight: 20,
  },
  threadItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#2f343a',
  },
  activeThreadItem: {
    backgroundColor: '#374151',
  },
  threadInfo: {
    flex: 1,
  },
  threadTitle: {
    fontSize: 16,
    color: '#ffffff',
    fontWeight: '600',
  },
  threadDate: {
    fontSize: 14,
    color: '#9ca3af',
    marginTop: 4,
  },
  threadMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  messageCount: {
    fontSize: 12,
    color: '#6b7280',
    backgroundColor: '#374151',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    minWidth: 20,
    textAlign: 'center',
  },
  deleteButton: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#dc2626',
    borderRadius: 12,
  },
  deleteIcon: {
    fontSize: 16,
    color: '#ffffff',
    fontWeight: 'bold',
  },
  activeIndicator: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#2563eb',
    marginLeft: 8,
  },
  codeBlock: {
    backgroundColor: '#1a1a1a',
    borderRadius: 8,
    padding: 12,
    marginVertical: 4,
    borderLeftWidth: 3,
    borderLeftColor: '#2563eb',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
      },
      android: {
        elevation: 5,
      },
    }),
  },
  codeLanguage: {
    fontSize: 12,
    color: '#9ca3af',
    fontWeight: '600',
    marginBottom: 8,
    textTransform: 'uppercase',
    fontFamily: Platform.select({
      ios: 'System',
      android: 'Roboto',
    }),
  },
  codeText: {
    fontSize: 14,
    color: '#e5e7eb',
    lineHeight: 20,
    fontFamily: Platform.select({
      ios: 'Courier New',
      android: 'monospace',
    }),
  },
  settingsButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginRight: 8,
  },
  settingsModal: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  settingsModalContent: {
    backgroundColor: '#1f2937',
    borderRadius: 12,
    padding: 20,
    width: '80%',
    maxHeight: '60%',
  },
  settingsTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#f9fafb',
    marginBottom: 16,
    textAlign: 'center',
  },
  settingsOption: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#374151',
  },
  settingsOptionText: {
    fontSize: 16,
    color: '#f9fafb',
  },
  settingsModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  settingsModalContainer: {
    backgroundColor: '#1f2937',
    borderRadius: 12,
    padding: 20,
    width: '90%',
    maxHeight: '80%',
  },
  settingsModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#374151',
  },
  settingsModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#f9fafb',
    marginLeft: 8,
  },
  settingsFormGroup: {
    marginBottom: 16,
  },
  settingsLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#f9fafb',
    marginBottom: 8,
  },
  settingsInput: {
    backgroundColor: '#374151',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: '#f9fafb',
    borderWidth: 1,
    borderColor: '#4b5563',
  },
  settingsTextArea: {
    backgroundColor: '#374151',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: '#f9fafb',
    borderWidth: 1,
    borderColor: '#4b5563',
    minHeight: 80,
    textAlignVertical: 'top',
  },
  emailInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#374151',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#4b5563',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  emailInput: {
    flex: 1,
    fontSize: 16,
    color: '#ffffff',
    paddingVertical: 0,
  },
  emailSuffix: {
    fontSize: 16,
    color: '#9ca3af',
    marginLeft: 4,
  },
  copyButton: {
    marginLeft: 8,
    padding: 4,
  },
  settingsHelperText: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 4,
    fontStyle: 'italic',
  },
});

// Markdown theme for react-native-markdown-display
export const markdownTheme = {
  body: {
    color: '#e5e7eb',
    fontSize: 16,
    lineHeight: 24,
  },
  heading1: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '600',
    marginVertical: 16,
  },
  heading2: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '600',
    marginVertical: 14,
  },
  heading3: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '600',
    marginVertical: 12,
  },
  heading4: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    marginVertical: 10,
  },
  heading5: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    marginVertical: 8,
  },
  heading6: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
    marginVertical: 6,
  },
  paragraph: {
    marginVertical: 8,
  },
  link: {
    color: '#60a5fa',
    textDecorationLine: 'underline',
  },
  list_item: {
    flexDirection: 'row',
    marginVertical: 4,
  },
  bullet_list: {
    marginVertical: 8,
  },
  ordered_list: {
    marginVertical: 8,
  },
  bullet_list_icon: {
    color: '#9ca3af',
    marginRight: 8,
  },
  ordered_list_icon: {
    color: '#9ca3af',
    marginRight: 8,
  },
  code_inline: {
    backgroundColor: '#374151',
    color: '#f3f4f6',
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 4,
    fontFamily: Platform.select({
      ios: 'Courier New',
      android: 'monospace',
    }),
  },
  blockquote: {
    backgroundColor: 'rgba(37, 99, 235, 0.1)',
    borderLeftWidth: 4,
    borderLeftColor: '#2563eb',
    padding: 12,
    marginVertical: 8,
    borderRadius: 4,
  },
  blockquoteText: {
    color: '#e5e7eb',
    fontStyle: 'italic',
  },
  code_block: {
    backgroundColor: '#1a1a1a',
    borderRadius: 8,
    padding: 12,
    marginVertical: 8,
  },
  fence: {
    backgroundColor: '#1a1a1a',
    borderWidth: 0,
    borderRadius: 8,
    padding: 12,
    marginVertical: 8,
  },
  table: {
    borderWidth: 1,
    borderColor: '#374151',
    borderRadius: 8,
    marginVertical: 8,
  },
  thead: {
    backgroundColor: '#1f2937',
  },
  th: {
    padding: 12,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#374151',
  },
  thText: {
    color: '#f9fafb',
    fontWeight: '600',
  },
  tr: {
    flexDirection: 'row',
  },
  td: {
    flex: 1,
    padding: 12,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#374151',
  },
  tdText: {
    color: '#e5e7eb',
  },
  hr: {
    backgroundColor: '#374151',
    height: 1,
    marginVertical: 16,
  },
};